### ISSUE TITLE
Crash When Inserting Items of a Different Type

### ISSUE THREAD

**Issue by MorningSage** [branchpanic/stockpile#100]
When using a hopper (or presumably any other block that automatically inserts items), placing items that are of a different type into a non-empty barrel results in a crash.

To replicate:
• Fill a barrel with at least one of any item
• Use a hopper to try to insert any other item of a different type

This error occurs on the latest version posted to CurseForge.  I haven't looked into much, so if you need me to open a ticket on LibBlockAttributes, I can do that, too.  Not sure exactly where the issue lies.

Here’s the full crash report:
https://pastebin.com/CPksU9Di

The jar block uses the vanilla hopper logic to insert items as seen here:
https://github.com/CoolMineman/Plant-In-A-Jar/blob/5b8e5df007fae0d58fa828d2b8183dc1126b5425/src/main/java/io/github/coolmineman/plantinajar/JarBlockEntity.java#L78

**Comment by Katorone** [comment]
I'm having a similar issue with Tech Reborn Storage Units trying put push items to a Stockpile barrel.
https://pastebin.com/a0FCmA7V

**Comment by branchpanic** [comment]
Apologies for the issue, I probably missed something when upgrading LibBlockAttributes. This is probably a significant enough bug to warrant a fix even though I'm not working on the mod actively, so stay tuned and I'll try to push something relatively soon.

**Comment by Katorone** [comment]
Thank you! Apart from this issue, Stockpile is the best YABBA-style mod for Fabric. <3

**Comment by branchpanic** [comment]
A quick update, it looks like this is actually originating from Universal Components. I'm closing the issue here since it looks like they have it under control. Keep an eye out for an update there!

If you want to play with Stockpile (or just get your world out of a crash loop) you can try temporarily disabling UC and any mods that include it.

**Comment by Katorone** [comment]
Thanks !
