### ISSUE TITLE
No License, and other suggestions.

### ISSUE THREAD

**Issue by UpcraftLP** [branchpanic/stockpile#101]
Hello, I was wondering, the CurseForge page says your project is under MIT, yet this repo doesn't have a license file (nor anything in the readme regarding licensing), effectively making the source code All Rights Reserved.

I'm asking because I saw this note you left on the curseforge page:

> Note: Stockpile isn't being actively developed, but will still receive updates for major Minecraft versions to preserve compatibility. If you are a Fabric mod developer interested in taking over the project, please inquire on GitHub.

I would like to take over development of the project. That is, if you don't mind me converting the source code to java, as that's what I'm more familiar with, and which might help get more people interested in helping out development in the future.

**Comment by branchpanic** [comment]
That's a goof on my part... I could've sworn the LICENSE file was there, honest! Stockpile is supposed to be MIT licensed and I'll update the repo with it shortly. 

Thanks for your interest in maintaining the project. You are free to rewrite it in whatever language you want (sorry in advance about my weird API). My only request is that compatibility is maintained if possible. Let me know when you make some headway and I'll transfer the repo and CF page.

**Comment by UpcraftLP** [comment]
Ok, I will try my best. Do you know any mods that actually use the API, so I can make sure nothing breaks?

**Comment by branchpanic** [comment]
I don't think so. As far as I'm aware no mods have a hard dependency on Stockpile.

**Comment by branchpanic** [comment]
Assuming there hasn't been any progress on this since it's been over a year, but thankfully, we seem to have found new maintainers. Thanks again for your interest.
