### ISSUE TITLE
I would like to be your new maintainer

### ISSUE THREAD

**Issue by Mysticpasta1** [branchpanic/stockpile#104]
I would love to maintain stockpile for all versions and possibly in the future make new ones, fix bugs is also priority with me so I will do that too.

contact me on discord if you need more info Hauntedpasta1#8200

github: Mysticpasta1
curseforge: mysticpasta1

**Comment by branchpanic** [comment]
Thanks for your interest, I sent a friend request.

**Comment by Mysticpasta1** [comment]
accepted :D
