### ISSUE TITLE
Pipe system issue in 1.0.0

### ISSUE THREAD

**Issue by Flo2018v** [branchpanic/stockpile#40]
So I was using a pipe system as an automatic item sorter in versions prior to 1.0.0. To upgrade my mod, I simple inverted the pipes, extracted everything and put all my items in chests. Then I deleted all the barrels, updated the version and placed te new barrel. The pipe system is simple pipes from 1.14 fabric.

However, something goes wrong, on the 1.0.0 stockpile, there are 2 issues. First: the barrel count does not update unless you interact with the barrel. 2nd: when an item is attempted to be inserted by the pipe and the item is not accepted in that barrel, now instead going back, it is just deleted. So if you attempt put a diamond in a gold barrel, you loose the diamond. So basicly now my storage system is useless since I cannot send items or everything will be lost. I have to keep my items in my chests now

**Comment by branchpanic** [comment]
Thanks for the bug report. I was able to reproduce this and discovered some other unexpected behavior with SimplePipes. I'll hopefully be able to come up with a hotfix soon.

**Comment by branchpanic** [comment]
A temporary fix has been implemented and version 1.0.1 will be uploaded to Curse shortly. If the problem persists in the same form feel free to re-open the issue!
