### ISSUE TITLE
Item duping with hat

### ISSUE THREAD

**Issue by Knito58** [branchpanic/stockpile#41]
Tried the hat and had made some barrels. Pressing "G" and boom! All my hotbar items gone. Where? Into my barrels in the rest of my player inventory, which were all paired in nice stacks of 2. Now one stack received my diamond sword. Now I have two diamond swords after building the blocks and emptying them. Same with my diamond pickaxe, shovel, water buckets and torches. I don't complain about doubling my valuable items but I have a strong feeling that this is not the inteded behaviour. But I can say: I love that stylish new hat!

**Comment by Knito58** [comment]
Another one:
The barrel's item indicating image is "dark". This applies to "locked" and "not-locked" barrels.
Good thing is that when a barrel is initialized with an item it is locked to that item. Makes sense.

**Comment by branchpanic** [comment]
Nice catch-- I forgot the recipe yielded two barrels, which is the only time they ever stack. This should be a rather simple fix.

I'm also going to go ahead and separate out your second report here into another issue since I'm not exactly sure how to fix it yet. Thanks for the report!

**Comment by Knito58** [comment]
Thanks for dividing the ticket. I will behave in the future and not do multiple reports in one ticket any more.
