### ISSUE TITLE
Kotlin

### ISSUE THREAD

**Issue by Flo2018v** [branchpanic/stockpile#43]
Hi! It is me again. I found another bug with Kotlin this time.

When you install kotlin as a dependency for other mods, that makes the game crash, but some mods don’t work without it

**Comment by branchpanic** [comment]
Thanks for the diligent bug reporting! It's been brought to my attention that there are a few problems with how Stockpile currently embeds the Kotlin dependency, so in the next release, it won't be included as part of the mod jar and should thus eliminate this problem. If you managed to snag a log from the crash, feel free to paste it into a [Gist](https://gist.github.com/) and link it here (if you didn't, don't worry-- I'll probably be able to fix the issue without it).
