### ISSUE TITLE
java.lang.Exception: Could not find adapter 'kotlin' (mod stockpile!)

### ISSUE THREAD

**Issue by ruphskunk** [branchpanic/stockpile#48]
Just updated stockpile to stockpile-1.0.2+1.14, and minecraft crashes with `java.lang.Exception: Could not find adapter 'kotlin' (mod stockpile!)`

Previous version worked without this error

**Comment by branchpanic** [comment]
Stockpile 1.0.2 does not bundle the Kotlin language adapter, as it adds extra bloat and redundancy to modpacks. You'll have to [download it separately on Curse](https://minecraft.curseforge.com/projects/fabric-language-kotlin). I've updated the project page to reflect this. Please re-open the issue if this problem persists!
