### ISSUE TITLE
Unable to add first item unless it's in shield slot

### ISSUE THREAD

**Issue by poboy975** [branchpanic/stockpile#51]
Like the title says, I'm unable to add anything to a barrel unless it's first in the shield slot, after that I can add from inventory like normal.

**Comment by branchpanic** [comment]
In testing, I've been able to add and extract from barrels properly-- it seems like I'm missing something. Could you perhaps come up with a few specific steps to reproduce this issue? Additionally, if any other mods are present, could you provide a list?

**Comment by poboy975** [comment]
Ok, I just loaded up my game, and I'm able to place items as normal. So possibly just a temp glitch. Everything is working the way it's supposed to now.

**Comment by branchpanic** [comment]
In that case I'll close it for now, glad it works! If something similar happens again feel free to return to this issue.
