### ISSUE TITLE
Using an equipped shield on a barrel breaks barrels for that player

### ISSUE THREAD

**Issue by branchpanic** [branchpanic/stockpile#54]
Last reproduced on 1.0.3. This is really weird, no idea where to start with it.

Also, shields don't render properly in the display.

**Comment by Napkin** [comment]
Glad you created this issue again. I was about to re-open the closed issue about this. Anything I can do to help?

**Comment by branchpanic** [comment]
Thanks for your interest! I'll be delving into this issue on the weekend but I think at this point most of the work is just on the debugging end. If I come up with anything, though, I'll post it in this thread.

**Comment by branchpanic** [comment]
I've figured this one out and a fix should be included in the next version, which should come out within a day or two.
