### ISSUE TITLE
Barrel's Voiding Items

### ISSUE THREAD

**Issue by NinjaPhenix** [branchpanic/stockpile#56]
In Stockpile v1.0.4+1.14.1 (latest) items inputted into barrels through a hopper get voided after 1985 items, upgrading the barrel increases this threshold but they still get voided  (for iron upgrade  its 4033)

**Comment by branchpanic** [comment]
I can already tell exactly why this is happening and it's a pretty dumb mistake. Thanks for including specific numbers in your report! This should be fixed shortly.

**Comment by branchpanic** [comment]
Fixed. If you encounter other similar issues feel free to re-open.
