### ISSUE TITLE
Barrel's Voiding Items #2

### ISSUE THREAD

**Issue by NinjaPhenix** [branchpanic/stockpile#57]
So barrels now correctly fill upto their limit when inputting items from a hopper however once they are at their limit any further items inputted via hopper get voided 🤷‍♂

**Comment by branchpanic** [comment]
When one door of opportunity closes in life, another opens. A similar principle applies to item deletion bugs in Stockpile. Expect a hotfix today/tomorrowish.

**Comment by branchpanic** [comment]
Just to confirm why this is happening on my end: has this always been an issue or is it a recent bug? If it's something that only just started happening, do you recall a version where barrels behaved as expected?

**Comment by NinjaPhenix** [comment]
I've only recently started using the mod so as far as I'm aware it has always been like this, I can test older versions if you would like.

**Comment by branchpanic** [comment]
That's fine, I can take care of that part. I was just wondering if you happened to know anything about other versions.

**Comment by branchpanic** [comment]
1.0.6 has fixed this issue and will be uploaded shortly. Let's hope a 3rd iteration isn't needed.
