### ISSUE TITLE
Cannot remove last item from Barrel - eating items

### ISSUE THREAD

**Issue by Arkhayla** [branchpanic/stockpile#60]
The latest update has made it so you can't remove the last item from a barrel. I am trying to test it further but somehow it ate my pickaxe and 15 of 16 quartz blocks.

1. I put 16 quartz blocks in a barrel by mistake, tried to remove them all and was left with 1* (Unlocked Barrel) Quartz Block I couldn't remove. 
2. I then accidentally right clicked with my pickaxe and it overwrote the 1 Quartz Block in the barrel.
3. I tried to remove the pickaxe and couldn't, then clicked with the Quartz Blocks again and it overwrote the pickaxe with 15 Quartz Blocks.
4. I was only able to remove 1 of them from the barrel after that, it was stuck at 14* Quartz Blocks
5. I used an axe to pick up the barrel and it showed as empty.

Sorry if that is confusing, tried to go step by step - I'll update with more info if I can figure it out more clearly

**Comment by branchpanic** [comment]
Thanks for the detailed issue. The steps to reproduce are appreciated! I'll take a look at this when I get the chance.

**Comment by branchpanic** [comment]
This issue should be solved in 1.0.7 which was just uploaded. Thanks for your patience!
