### ISSUE TITLE
Unlocked barrels delete items instead of dropping them

### ISSUE THREAD

**Issue by nhilerion** [branchpanic/stockpile#61]
If i unlock a barrel and shift click it to give a stack the items doesnt appear and when i right click it with an empty hand it becomes empty.

**Comment by nhilerion** [comment]
seems like only if its the last stack

**Comment by branchpanic** [comment]
Thanks for reporting the issue! This looks like it might be related to #60 but I won't mark it as a duplicate yet as I have yet to confirm.

**Comment by branchpanic** [comment]
1.0.7 was just uploaded and should fix this.
