### ISSUE TITLE
Display barrel info on HUD

### ISSUE THREAD

**Issue by branchpanic** [branchpanic/stockpile#67]
The status bar isn't really suited for this. Having info about upgrades, contents, and more right on the screen when looking at a barrel would probably be a lot more helpful.

**Comment by coldino** [comment]
Would be nice to support WAILA/HWYLA and/or The One Probe for this sort of thing.

**Comment by branchpanic** [comment]
Partially implemented this in #72. More specifically, upgrades will be visible when hovering over a barrel with an upgrade-related item. I still want to do more with this and integrate it with (at least one of) the mods you mentioned, so I'm leaving the issue open for now.

**Comment by branchpanic** [comment]
HWYLA support was added in 1.1.0. Hopefully this should hold things over for now. I'll make a more specific issue in the future if I want to do more with overlays.
