### ISSUE TITLE
Update build for 1.14.3 if necessary

### ISSUE THREAD

**Issue by branchpanic** [branchpanic/stockpile#70]
Putting this here since I might not be able to get to it for a bit. Just want to make sure that people are aware that I know a new version came out. Here's to hoping it doesn't break anything!!!

**Comment by antisane** [comment]
This works (sort of) with fabric 1.14.3, with only 1 problem... for some reason a barrel will only hold 15 stacks, even though it says 15/32 stacks when you try to put more in. Bug persists even if you upgrade the barrel (then it says 15/64 stacks, and still won't let me put more in.

**Comment by branchpanic** [comment]
Thanks for the info. I've been really busy with moving lately so having a report like this is really helpful. I'm not sure when I'll be able to get to it but it should be relatively soon (in the slim chance that any interested devs are watching, PRs are welcome).

**Comment by antisane** [comment]
Not a problem, we all have a life outside Minecraft. I'll just use Iron Barrels for now. Hope all goes well with your move :)

**Comment by branchpanic** [comment]
Had a spare minute so I just pushed 1.0.8 which properly supports 1.14.3 and has some additional upgrade-related features I've been working on. I think a proper update fixed the issue you mentioned, but if the problem persists (or any new ones arise) let me know!

**Comment by antisane** [comment]
Update works great so far, thanks!

**Comment by branchpanic** [comment]
Awesome!
