### ISSUE TITLE
Bug : Do not put shukler box in barrel

### ISSUE THREAD

**Issue by HappySeal** [branchpanic/stockpile#85]
It is a heavy bug that if you put empty/filled shulker box in barrel, every shulker box you put after that will be converted to it. It will end up with item duplication or item deleting

**Comment by branchpanic** [comment]
Thanks for your issue report. This looks like the same problem as #83 which will be fixed in 1.1.0 later today, however I'll leave it open for now since I'm not able to confirm.

**Comment by HappySeal** [comment]
Hello, thanks for the response, I experimented with some of the other items and problem is not about shulkers it about items with nbt data. I hope you keep an eye on that. Thanks

**Comment by branchpanic** [comment]
Alright the version that fixes this should be uploaded soon. If you run into any more issues we can continue discussing on #83 because it was the first report of this bug.
