### ISSUE TITLE
Bug with hat unpack

### ISSUE THREAD

**Issue by kohanis** [branchpanic/stockpile#87]
If here 1+ empty slot in inventory hat trying to unload items to all this slots for some reason. And can't. So, items disappear

**Comment by branchpanic** [comment]
I'm away from my PC for 2 days but will fix when I get back. Assuming this has been confirmed since I've received multiple reports of the exact same thing.

**Comment by kohanis** [comment]
1 of them on curseforge was me, but i tested this around 10 mins with only fabric and kotlin api installed. I'm sure about

**Comment by branchpanic** [comment]
Should be fixed in 1.1.2, let me know if you have any other issues!
