### ISSUE TITLE
Host jars on GH package registry

### ISSUE THREAD

**Issue by branchpanic** [branchpanic/stockpile#89]
Just realized that I have access to this now so it'd be nice. I don't think anyone's developing against Stockpile at this point but it can't hurt to make the option available.

**Comment by UpcraftLP** [comment]
github packages aren't *really* useful for modders, since you need to authenticate with github for interacting with them (this includes downloadijng files)

**Comment by branchpanic** [comment]
Ah, had no idea. That's pretty annoying.
