### ISSUE TITLE
1.16 Update

### ISSUE THREAD

**Issue by jcaimeey** [branchpanic/stockpile#98]
Any chance this will get a 1.16 update? It's one of the last two mods I need in order for my server to  be able to upgrade to 1.16.  I tried to do it myself, but I'm not familiar enough with Minecraft modding or Java in general to make much progress.

**Comment by branchpanic** [comment]
I wouldn't say I'm working on the mod actively, but since I noticed a few people asking for a 1.16 update I'll see how difficult it is. If it's not too involved I'll port it over! But if I have to rewrite something like the barrel renderer again, it's probably the end of the line for me.

**Comment by branchpanic** [comment]
Huh, that was pretty simple. Update on Curse soon!

![image](https://user-images.githubusercontent.com/3802908/88462626-cd110c80-ce7a-11ea-8d48-ad10962c91e7.png)
