### ISSUE TITLE
The texture of the block below the trash can disappears

### ISSUE THREAD

**Issue by linzexin022** [branchpanic/stockpile#99]
Hi there, I found the texture of the block below the trash can disappears:
![image](https://user-images.githubusercontent.com/59003232/88472687-2d21b480-cf48-11ea-834c-f3cb25f2fa6b.png)

**Comment by branchpanic** [comment]
Ah darn, I forgot something while upgrading. I'm assuming this is the new 1.16 version, right? I'll fix it soon. Thanks for notifying me!

**Comment by linzexin022** [comment]
Yes, it's the 1.16.1 version.

**Comment by branchpanic** [comment]
Forgot to update the issue but this is fixed in the latest release!
